//HintName: GeneratedMediator.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using AdvGenFlow;
using Microsoft.Extensions.DependencyInjection;

internal sealed class GeneratedMediator : IMediator
{
    private readonly IServiceProvider _serviceProvider;
    public GeneratedMediator(IServiceProvider serviceProvider)
        => _serviceProvider = serviceProvider;

    public Task<TResponse> Send<TResponse>(IRequest<TResponse> request,
        CancellationToken cancellationToken = default)
    {
        return request switch
        {
            PingCommand __r => (Task<TResponse>)(object)SendCore_PingCommand(__r, cancellationToken),
            _ => throw new InvalidOperationException($"No handler registered for {request.GetType().Name}")
        };

        Task<string> SendCore_PingCommand(PingCommand r, CancellationToken ct)
        {
            var handler = _serviceProvider.GetRequiredService<IRequestHandler<PingCommand, string>>();
            var behaviors = _serviceProvider.GetServices<IPipelineBehavior<PingCommand, string>>();
            return PipelineBuilder.Build(() => handler.Handle(r, ct), behaviors, r, ct);
        }

    }

    public Task Publish<TNotification>(TNotification notification,
        CancellationToken cancellationToken = default)
        where TNotification : INotification
    {
        var handlers = _serviceProvider.GetServices<INotificationHandler<TNotification>>();
        return Task.WhenAll(handlers.Select(h =>
        {
            try { return h.Handle(notification, cancellationToken); }
            catch (Exception ex) { return Task.FromException(ex); }
        }));
    }

    public IAsyncEnumerable<TResponse> CreateStream<TResponse>(IStreamRequest<TResponse> request,
        CancellationToken cancellationToken = default)
    {
        return request switch
        {
            _ => throw new InvalidOperationException($"No stream handler registered for {request.GetType().Name}")
        };
    }
}
