//HintName: GeneratedMediator.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using AdvGenFlow;
using Microsoft.Extensions.DependencyInjection;

internal sealed class GeneratedMediator : IMediator
{
    private readonly IServiceProvider _serviceProvider;
    public GeneratedMediator(IServiceProvider serviceProvider)
        => _serviceProvider = serviceProvider;

    public Task<TResponse> Send<TResponse>(IRequest<TResponse> request,
        CancellationToken cancellationToken = default)
    {
        return request switch
        {
            _ => throw new InvalidOperationException($"No handler registered for {request.GetType().Name}")
        };
    }

    public Task Publish<TNotification>(TNotification notification,
        CancellationToken cancellationToken = default)
        where TNotification : INotification
    {
        var handlers = _serviceProvider.GetServices<INotificationHandler<TNotification>>();
        return Task.WhenAll(handlers.Select(h =>
        {
            try { return h.Handle(notification, cancellationToken); }
            catch (Exception ex) { return Task.FromException(ex); }
        }));
    }

    public IAsyncEnumerable<TResponse> CreateStream<TResponse>(IStreamRequest<TResponse> request,
        CancellationToken cancellationToken = default)
    {
        return request switch
        {
            _ => throw new InvalidOperationException($"No stream handler registered for {request.GetType().Name}")
        };
    }
}
