using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace AdvGenFlow.SourceGen;

[Generator]
public sealed class MediatorDispatchGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlerCandidates = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetHandlerInfo(ctx))
            .Where(static info => info is not null)
            .Collect();

        context.RegisterSourceOutput(handlerCandidates, static (spc, handlers) =>
            Execute(spc, handlers!));
    }

    private static HandlerInfo? GetHandlerInfo(GeneratorSyntaxContext ctx)
    {
        if (ctx.Node is not ClassDeclarationSyntax classDecl) return null;
        var symbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
        if (symbol is null || symbol.IsAbstract) return null;

        var requestHandlers = new List<(string req, string resp)>();
        var notificationHandlers = new List<string>();
        var streamHandlers = new List<(string req, string resp)>();

        foreach (var iface in symbol.AllInterfaces)
        {
            if (!iface.IsGenericType) continue;
            var name = iface.OriginalDefinition.ToDisplayString();

            if (name == "AdvGenFlow.IRequestHandler<TRequest, TResponse>")
            {
                requestHandlers.Add((
                    iface.TypeArguments[0].ToDisplayString(),
                    iface.TypeArguments[1].ToDisplayString()));
            }
            else if (name == "AdvGenFlow.INotificationHandler<TNotification>")
            {
                notificationHandlers.Add(iface.TypeArguments[0].ToDisplayString());
            }
            else if (name == "AdvGenFlow.IStreamRequestHandler<TRequest, TResponse>")
            {
                streamHandlers.Add((
                    iface.TypeArguments[0].ToDisplayString(),
                    iface.TypeArguments[1].ToDisplayString()));
            }
        }

        if (requestHandlers.Count == 0 && notificationHandlers.Count == 0 && streamHandlers.Count == 0)
            return null;

        return new HandlerInfo(requestHandlers, notificationHandlers, streamHandlers);
    }

    private static void Execute(SourceProductionContext context, IEnumerable<HandlerInfo> allHandlers)
    {
        var requestHandlers = new List<(string req, string resp)>();
        var notificationHandlers = new List<string>();
        var streamHandlers = new List<(string req, string resp)>();

        foreach (var info in allHandlers)
        {
            requestHandlers.AddRange(info.RequestHandlers);
            notificationHandlers.AddRange(info.NotificationHandlers);
            streamHandlers.AddRange(info.StreamHandlers);
        }

        var source = GenerateSource(requestHandlers, notificationHandlers, streamHandlers);
        context.AddSource("GeneratedMediator.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static string GenerateSource(
        List<(string req, string resp)> requestHandlers,
        List<string> notificationHandlers,
        List<(string req, string resp)> streamHandlers)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using AdvGenFlow;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("internal sealed class GeneratedMediator : IMediator");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly IServiceProvider _serviceProvider;");
        sb.AppendLine("    public GeneratedMediator(IServiceProvider serviceProvider)");
        sb.AppendLine("        => _serviceProvider = serviceProvider;");
        sb.AppendLine();

        // Send
        sb.AppendLine("    public Task<TResponse> Send<TResponse>(IRequest<TResponse> request,");
        sb.AppendLine("        CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        return request switch");
        sb.AppendLine("        {");
        foreach (var (req, resp) in requestHandlers)
        {
            var safeName = req.Replace(".", "_").Replace("<", "_").Replace(">", "_").Replace(",", "_").Replace(" ", "");
            sb.AppendLine($"            {req} __r => (Task<TResponse>)(object)SendCore_{safeName}(__r, cancellationToken),");
        }
        sb.AppendLine("            _ => throw new InvalidOperationException($\"No handler registered for {request.GetType().Name}\")");
        sb.AppendLine("        };");
        if (requestHandlers.Count > 0)
        {
            sb.AppendLine();
        }
        foreach (var (req, resp) in requestHandlers)
        {
            var safeName = req.Replace(".", "_").Replace("<", "_").Replace(">", "_").Replace(",", "_").Replace(" ", "");
            sb.AppendLine($"        Task<{resp}> SendCore_{safeName}({req} r, CancellationToken ct)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var handler = _serviceProvider.GetRequiredService<IRequestHandler<{req}, {resp}>>();");
            sb.AppendLine($"            var behaviors = _serviceProvider.GetServices<IPipelineBehavior<{req}, {resp}>>();");
            sb.AppendLine($"            return PipelineBuilder.Build(() => handler.Handle(r, ct), behaviors, r, ct);");
            sb.AppendLine("        }");
            sb.AppendLine();
        }
        sb.AppendLine("    }");
        sb.AppendLine();

        // Publish
        sb.AppendLine("    public Task Publish<TNotification>(TNotification notification,");
        sb.AppendLine("        CancellationToken cancellationToken = default)");
        sb.AppendLine("        where TNotification : INotification");
        sb.AppendLine("    {");
        sb.AppendLine("        var handlers = _serviceProvider.GetServices<INotificationHandler<TNotification>>();");
        sb.AppendLine("        return Task.WhenAll(handlers.Select(h =>");
        sb.AppendLine("        {");
        sb.AppendLine("            try { return h.Handle(notification, cancellationToken); }");
        sb.AppendLine("            catch (Exception ex) { return Task.FromException(ex); }");
        sb.AppendLine("        }));");
        sb.AppendLine("    }");
        sb.AppendLine();

        // CreateStream
        sb.AppendLine("    public IAsyncEnumerable<TResponse> CreateStream<TResponse>(IStreamRequest<TResponse> request,");
        sb.AppendLine("        CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        return request switch");
        sb.AppendLine("        {");
        foreach (var (req, resp) in streamHandlers)
        {
            sb.AppendLine($"            {req} __r => (IAsyncEnumerable<TResponse>)(object)");
            sb.AppendLine($"                _serviceProvider.GetRequiredService<IStreamRequestHandler<{req}, {resp}>>()");
            sb.AppendLine($"                    .Handle(__r, cancellationToken),");
        }
        sb.AppendLine("            _ => throw new InvalidOperationException($\"No stream handler registered for {request.GetType().Name}\")");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private sealed class HandlerInfo(
        List<(string req, string resp)> requestHandlers,
        List<string> notificationHandlers,
        List<(string req, string resp)> streamHandlers)
    {
        public IReadOnlyList<(string req, string resp)> RequestHandlers => requestHandlers;
        public IReadOnlyList<string> NotificationHandlers => notificationHandlers;
        public IReadOnlyList<(string req, string resp)> StreamHandlers => streamHandlers;
    }
}
